import { Injectable } from '@angular/core';
import { Language } from '../models/language.interface';
import { LanguageService } from './language.service';

@Injectable({
  providedIn: 'root'
})
export class TextService {
  static language: String = LanguageService.getLanguageCodeOnly();
  static textFr: Language = {
    dark: 'Sombre',
    light: 'Clair',
    rtl: 'Dag',
    ltr: 'Gad',
    learnMore: 'Plus d\'information',
    home: 'Accueil',
    homeDesc: 'Amédée est un auteur-compositeur-interprète. Il grandit en banlieue lyonnaise.',
    back: 'Retour',
    blog: 'Blog',
    contact: 'Contact',
    about: 'À propos',
    readMore: 'lire la suite',
    privacyPolicy: 'Politique de confidentialité',
    pages: 'Pages',
    sitemap: 'Sitemap',
    post: 'Article',
    notFound: '404',
    notFoundDesc: 'La page que vous essayez d\'atteindre n\'est pas disponible actuellement. Cela peut être dû au fait que la page n\'existe pas ou a été déplacée.',
    goHome: 'Retour à l\'accueil',
    notFoundTitle: 'Page non trouvée',
    search: 'Rechercher',
    listenToMe: 'Écoutez-moi',
    latestNovelty: 'Dernière nouveauté',
    myProjects: 'Mes projets',
    biography: 'Biographie',
    gallery: 'Galerie',
    access: 'Accéder',
    download: 'Télécharger',
    listOfEvents: 'Liste des évènements',
    listOfVideos: 'Liste des vidéos',
    video: 'Vidéo',
    watchNow: 'Visionner',
    seeAll: 'Voir tout',
    lyrics: 'Paroles',
    referringToMe: 'On parle de moi',
    subscribe: 'S\'abonner',
    subscribeSuccess: 'Merci de vous être abonné.',
    subscribeEmail: 'Veuillez saisir votre adresse e-mail',
    subscribeError: 'Une erreur est survenue, merci de réessayer.',
    subscribeInfo: 'Obtenez de l\'information de première main au sujet de',
    contactError: 'Une erreur est survenue, merci de réessayer.',
    contactSuccess: 'Merci pour votre message, je vous répondrais dans les meilleurs délais.',
    send: 'Envoyer',
    contactName: 'Votre nom',
    contactEmail: 'Votre email',
    contactMessage: 'Votre message',
    contactTitle: 'Contactez-moi',
    contactDesc: 'Contactez-moi.',
    cookieMessage: 'Ce site web utilise des cookies pour vous assurer la meilleure expérience de navigation sur notre site.',
    cookieDismiss: 'OK, j\'ai compris!',
    cookieDeny: 'Refuser',
    cookiePolicy: 'Cookie Policy',
    cookieHeader: 'Cookies sur le site!',
    cookieAllow: 'Autoriser les cookies',
    listen: 'Écouter',
    emptyItems: 'Aucun élément à afficher pour le moment',
    articleList: 'Liste des articles',
    maintenance: 'Maintenance',
    maintenanceInProcess: 'Maintenance en cours',
    weWillbackSoon: 'Nous serons bientôt de retour',
    popularPosts: 'Articles populaires',
    close: 'Fermer',
  };
  static textEn: Language = {
    dark: 'Dark',
    light: 'Light',
    rtl: 'Rtl',
    ltr: 'Ltr',
    learnMore: 'Learn more',
    home: 'Home',
    homeDesc: 'Amédée is a singer-songwriter. He grew up in the Lyon suburbs.',
    back: 'Back',
    blog: 'Blog',
    contact: 'Contact',
    about: 'About me',
    readMore: 'read more',
    privacyPolicy: 'Privacy policy',
    pages: 'Pages',
    sitemap: 'Sitemap',
    post: 'Post',
    notFound: '404',
    notFoundDesc: 'The page you are attempting to reach is currently not available. This may be because the page does not exist or has been moved.',
    goHome: 'Back to home',
    notFoundTitle: 'Page not found',
    search: 'Search',
    listenToMe: 'Listen to me',
    latestNovelty: 'Latest novelty',
    myProjects: 'My projects',
    biography: 'Biography',
    gallery: 'Gallery',
    access: 'Access',
    download: 'Download',
    listOfEvents: 'List of events',
    listOfVideos: 'List of videos',
    video: 'Video',
    watchNow: 'Watch Now',
    seeAll: 'See all',
    lyrics: 'Lyrics',
    referringToMe: 'They\'re referring to me.',
    subscribe: 'Subscribe',
    subscribeSuccess: 'Thank you for subscribing.',
    subscribeEmail: 'Please enter your email address',
    subscribeError: 'An error has occurred, please try again.',
    subscribeInfo: 'Get first-hand information about',
    contactError: 'An error has occurred, please try again.',
    contactSuccess: 'Thank you for your message, I will answer you as soon as possible.',
    send: 'Send',
    contactName: 'Your name',
    contactEmail: 'Your email',
    contactMessage: 'Your message',
    contactTitle: 'Contact me',
    contactDesc: 'Contact me.',
    cookieMessage: "This website uses cookies to ensure you get the best experience on our website.",
    cookieDismiss: "Got it!",
    cookieDeny: "Refuse cookies",
    cookiePolicy: "Cookie Policy",
    cookieHeader: "Cookies used on the website!",
    cookieAllow: "Allow cookies",
    listen: 'Listen',
    emptyItems: 'No items to display at this time',
    articleList: 'Article list',
    maintenance: 'Maintenance',
    maintenanceInProcess: 'Maintenance in process',
    weWillbackSoon: 'We will be back soon',
    popularPosts: 'Popular posts',
    close: 'Close',
  };


  static getTextByLocal() {
    if (this.language === 'fr') {
      return this.textFr;
    } else {
      return this.textEn;
    }
  }

}
